var fa = {
    Save: "ذخیره",
    "Save all": "ذخیره همه",
    Rename: "تغییر نام",
    Open: "بازکردن",
    Edit: "ویرایش",
    Delete: "حذف",
    Folder: "پوشه",
    "Add New": "جدید",
    Size: "سایز",
    Date: "تاریخ",
    "back to parent folder": "back to parent folder",
    Download: "دانلود",
    Type: "نوع",
    Information: "اطلاعات",
    Files: "فایل‌ها",
    Table: "جدول",
    Cards: "کارها",
    Total: "مجموع",
    "Are you sure ?": "مطمئنید؟",
    Details: "جزئیات",
    "Enter a new name": "نام جدید",
    Add: "افزودن",
    "Select something": "انتخاب",
    "Download file": "دانلود فایل",
    Preview: "پیش‌نمایش",
    Refresh: "ریفرش",
    "Are you sure you want to exit without saving?": "Are you sure you want to exit without saving?",
    "Save before closing?": "Save before closing?",
    Copy: "کپی",
    Cut: "کات",
    Paste: "پیست",
    "Deleting...": "Deleting...",
    "Copying...": "Copying...",
    "Moving...": "Moving...",
    Folders: "Folders",
    "Search results": "Search results",
    "Search results in": "Search results in",
    "Search files and folders": "Search files and folders",
    "Add new file": "Add new file",
    "Add new folder": "Add new folder",
    "Upload file": "Upload file",
    folder: "پوشه",
    file: "فایل",
    archive: "آرشیو",
    audio: "صدا",
    image: "تصویر",
    video: "فیلم",
    code: "کد",
    document: "سند",
    of: "از",
    used: "استفاده شده",
    "Open item location": "Open item location",
    "Are you sure you want to delete": "Are you sure you want to delete",
    "these items:": "these items:",
    "this item:": "this item:",
    "Delete files": "Delete files",
    and: "و",
    "more file(s)": "فایلهای بیشتر",
    "Close the editor": "Close the editor",
    "Close this file": "Close this file",
    "Owner": "صاحب",
    "Permissions": "دسترسی‌ها",
    "Change Permissions": "تغییر دسترسی‌ها",
    "Set": "ثبت",
    "Extract": "گشودن",
    "Extract directory": "گشودن پوشه",
    "Extracting...": "در حال گشایش...",
    "Compress": "فشرده",
    "Compressing...": "درحال فشرده سازی...",
};