var fa = {
    Save: "ذخیره",
    "Save all": "ذخیره همه",
    Rename: "تغییر نام",
    Open: "بازکردن",
    Edit: "ویرایش",
    Delete: "حذف",
    Folder: "پوشه",
    "Add New": "جدید",
    Size: "سایز",
    Date: "تاریخ",
    "back to parent folder": "بازگشت به پوشه والد",
    Download: "دانلود",
    Type: "نوع",
    Information: "اطلاعات",
    Files: "فایل‌ها",
    Table: "جدول",
    Cards: "کارها",
    Total: "مجموع",
    "Are you sure ?": "مطمئنید؟",
    Details: "جزئیات",
    "Enter a new name": "نام جدید",
    Add: "افزودن",
    "Select something": "انتخاب",
    "Download file": "دانلود فایل",
    Preview: "پیش‌نمایش",
    Refresh: "ریفرش",
    "Are you sure you want to exit without saving?": "بدون ذخیره خارج می‌شوید؟",
    "Save before closing?": "ذخیره قبل از بستن",
    Copy: "کپی",
    Cut: "کات",
    Paste: "پیست",
    "Deleting...": "درحال حذف...",
    "Copying...": "درحال کپی...",
    "Moving...": "درحال انتقال...",
    Folders: "پوشه ها",
    "Search results": "نتایج جستجو",
    "Search results in": "نتایج جستجو در",
    "Search files and folders": "جستجوی فایل و پوشه‌ها",
    "Add new file": "درج فایل جدید",
    "Add new folder": "درج پوشه جدید",
    "Upload file": "آپلود فایل",
    folder: "پوشه",
    file: "فایل",
    archive: "آرشیو",
    audio: "صدا",
    image: "تصویر",
    video: "فیلم",
    code: "کد",
    document: "سند",
    of: "از",
    used: "استفاده شده",
    "Open item location": "بازکردن محل آیتم",
    "Are you sure you want to delete": "از پاک کردن اطمینان دارید؟",
    "these items:": "این آیتم‌ها:",
    "this item:": "این آیتم:",
    "Delete files": "حذف فایل‌ها",
    and: "و",
    "more file(s)": "فایلهای بیشتر",
    "Close the editor": "بستن ادیتور",
    "Close this file": "بستن فایل",
    "Owner": "صاحب",
    "Permissions": "دسترسی‌ها",
    "Change Permissions": "تغییر دسترسی‌ها",
    "Set": "ثبت",
    "Extract": "گشودن",
    "Extract directory": "گشودن پوشه",
    "Extracting...": "در حال گشایش...",
    "Compress": "فشرده",
    "Compressing...": "درحال فشرده سازی...",
};